-- Drop tables if they exist
DROP TABLE IF EXISTS "OrderItem" CASCADE;
DROP TABLE IF EXISTS "Orders" CASCADE;
DROP TABLE IF EXISTS "Customer" CASCADE;
DROP TABLE IF EXISTS "Product" CASCADE;
DROP TABLE IF EXISTS "Administrator" CASCADE;
DROP TABLE IF EXISTS "Country" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;

-- Create tables
CREATE TABLE "Country" (
    "countryId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(50) NOT NULL
);

CREATE TABLE "Category" (
    "categoryId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "superCategoryId" INT,
    "name" VARCHAR(50) NOT NULL,
    "description" VARCHAR(255),
    CONSTRAINT "fk_category_parent" FOREIGN KEY ("superCategoryId") REFERENCES "Category"("categoryId")
);

CREATE TABLE "Administrator" (
    "adminId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(20) UNIQUE NOT NULL,
    "password" VARCHAR(100) NOT NULL,
    "email" VARCHAR(30) NOT NULL UNIQUE,
    "salt" VARCHAR(100) NOT NULL
);

CREATE TABLE "Product" (
    "productId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(50) NOT NULL,
    "description" VARCHAR(255),
    "price" DECIMAL(10,2) NOT NULL,
    "stock" INT NOT NULL,
    "countryId" INT NOT NULL,
    "categoryId" INT NOT NULL,
    "adminId" INT NOT NULL,
    CONSTRAINT "fk_product_country" FOREIGN KEY ("countryId") REFERENCES "Country"("countryId"),
    CONSTRAINT "fk_product_category" FOREIGN KEY ("categoryId") REFERENCES "Category"("categoryId"),
    CONSTRAINT "fk_product_admin" FOREIGN KEY ("adminId") REFERENCES "Administrator"("adminId")
);

CREATE TABLE "Customer" (
    "customerId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(50) UNIQUE NOT NULL,
    "password" VARCHAR(100) NOT NULL,
    "email" VARCHAR(50) NOT NULL UNIQUE,
    "address" VARCHAR(255) NOT NULL, -- Fixed spelling from 'adress'
    "salt" VARCHAR(100) NOT NULL
);

CREATE TABLE "Orders" (
    "orderId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customerId" INT NOT NULL,
    "finalPrice" DECIMAL(10,2) NOT NULL,
    "orderDate" DATE NOT NULL,
    "orderStatus" VARCHAR(50) NOT NULL, -- Changed from INT to VARCHAR to fit inserts
    "orderType" VARCHAR(50) NOT NULL,   -- Changed from INT to VARCHAR to fit inserts
    "additionalInfo" VARCHAR(255),      -- Fixed spelling from 'addiitionalInfo'
    CONSTRAINT "fk_orders_customer" FOREIGN KEY ("customerId") REFERENCES "Customer"("customerId")
);

CREATE TABLE "OrderItem" (
    "orderId" INT NOT NULL,
    "orderItemId" INT NOT NULL,
    "productId" INT NOT NULL,
    "quantity" INT NOT NULL,
    "priceQuantity" DECIMAL(10,2) NOT NULL,
    CONSTRAINT "fk_orderitem_order" FOREIGN KEY ("orderId") REFERENCES "Orders"("orderId"),
    CONSTRAINT "fk_orderitem_product" FOREIGN KEY ("productId") REFERENCES "Product"("productId"),
    CONSTRAINT "PK_Order_OrderItem" PRIMARY KEY ("orderId", "orderItemId")
);

-- Trigger and Function to decrease stock on OrderItem insert
DROP TRIGGER IF EXISTS "trg_DecreaseStock" ON "OrderItem";
DROP FUNCTION IF EXISTS "fn_DecreaseStock"();

CREATE OR REPLACE FUNCTION "fn_DecreaseStock"()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE "Product"
    SET "stock" = "stock" - NEW."quantity"
    WHERE "productId" = NEW."productId";
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_DecreaseStock"
AFTER INSERT ON "OrderItem"
FOR EACH ROW
EXECUTE FUNCTION "fn_DecreaseStock"();
